---
repository: royalhackaway/royalhackaway.github.io
include: ["index.html", "_pages"]

display_ad: true

footer-description: "Royal Hackaway is a student-run group that hosts hackathons at Royal Holloway, University of London."

navs:
  -
    name: Home
    link: "#top"
  -
    name: Events
    link: "#future-events"
  -
    name: Sponsor us
    link: "/assets/pdf/sponsordeck.pdf"

socials:
  -
    icon: "facebook-white.svg"
    name: Facebook
    url: "https://facebook.com/royalhackaway"
  -
    icon: "twitter.svg"
    name: Twitter
    url: "https://twitter.com/royalhackaway"
  -
    icon: "github-mark.png"
    name: GitHub
    url: "https://github.com/royalhackaway"

email: hello@royalhackaway.com


collections:
  events:
    output: true
    permalink: /:slug


sass:
  style: compressed
  sass_dir: _sass
